name: Public Release CI

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  release-public:
    name: Public Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set variables
        id: vars
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/v}

      - name: Archive Source code
        run: zip -r BryanBot-v${{ steps.vars.outputs.version }}.zip * -x Dockerfile docker-compose.yml

      - name: Generate Checksums
        run: |
          md5sum BryanBot-v${{ steps.vars.outputs.version }}.zip pterodactyl-egg.json > md5-checksums.txt
          sha256sum BryanBot-v${{ steps.vars.outputs.version }}.zip pterodactyl-egg.json > sha256-checksums.txt
          sha512sum BryanBot-v${{ steps.vars.outputs.version }}.zip pterodactyl-egg.json > sha512-checksums.txt

      - uses: "softprops/action-gh-release@v2"
        with:
          name: "BryanBot v${{ steps.vars.outputs.version }}"
          prerelease: false
          files: |
            BryanBot-*.zip
            pterodactyl-egg.json
            *-checksums.txt
